# ejercicios

+ Crear un arreglo de ceros de longitud 12
+ Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
+ Crear un arreglo que tenga los números del 10 al 49
+ Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
+ Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
+ Calcular la media de un arreglo usando np.sum
+ Calcular la varianza de un arreglo usando np.sum y np.mean
+ Crear un array de números aleatorios usando np.random.randn.

In [4]:
import numpy as np

In [2]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr= np.zeros(10)
arr[5] = 10
print(arr)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [6]:
arr1 = np.arange(10,50,1)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
lista1 = [0,1,2]
lista2 = [3,4,5]
lista3 = [6,7,8]

lista4 = [lista1,lista2,lista3]
print(lista4)

listaGrande = lista1 + lista2 + lista3
i = np.array(listaGrande)
j = i.reshape(3,3)
print(j)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
arr2 = np.array(j)
print(arr2.ndim)

2


In [32]:
numeros_aleatorios = np.random.randint(1,500,100)
print(numeros_aleatorios)
sumatoria = numeros_aleatorios.sum()
print(sumatoria)
media = np.mean(numeros_aleatorios)
print(media)
varianza = np.var(numeros_aleatorios)
print(varianza)

[411 432 118 408 363 197 300 362 296 415 386 471 394 426  44 109  11 225
 229 365 457 192  14 290 206  80 334 122 167  48 493 479 470 227 140 219
 447 311 399  17 113 407   1  94  81 433  92 445 422 471 486  60 305 413
 385 372 204  95 122  21 205 150 276 297 428 308 407  32 278 352 307 285
 196 194  81 202 378 264 442 446 322  52 192 407 406  21 464 491 132 385
 273 289 110 407 116 286  62 259 248   4]
26550
265.5
21840.81


In [29]:
arr3= np.arange(1,11,1)
media = arr3.sum() / np.size(arr3)
print(media)

5.5


In [34]:
arr5 = np.arange(1,11,1)
media = np.mean(arr5)
cuadrado = (arr5 - media) ** 2
sumatoria = np.sum(cuadrado)
varianza = sumatoria / len(arr5)
print(varianza)

8.25


In [30]:
arr4_aleatorios = np.random.randint(1,10,5)
print(arr4_aleatorios)

[9 1 9 7 1]
